# Generated by Django 2.0.2 on 2018-04-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0005_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(blank=True, choices=[('EA', 'Em Andamento'), ('C', 'Concluído'), ('CD', 'Cancelada')], default='EA', max_length=2, verbose_name='Status'),
        ),
    ]
